### ISSUE TITLE
error while installing npm packages on winodws

### ISSUE THREAD

**Issue by 1saeedsalehi** [clover/remote-pay-cloud#40]
error in executing pre-install script generateDocs.sh
how can i resolve this problem on windows?

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! remote-pay-cloud-api@1.2.0 preinstall: `scripts/generateDocs.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the remote-pay-cloud-api@1.2.0 preinstall script 'scripts/generateDocs.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the remote-pay-cloud-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/generateDocs.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs remote-pay-cloud-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls remote-pay-cloud-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Saeed\Desktop\remote-pay-cloud-master\npm-debug.log

**Comment by mike-clover-com** [comment]
Please try
`npm install --ignore-scripts`

NPM does not include cross-platform scripting support. These scripts are supported on linux/Macintosh because that is what the library is  developed on, as well as support from the Heroku environment which is used for automatic deployment of some of the test applications.

The structure of the "scripts" portion of the package.json is strict, and cannot be changed. The individual contents of the script directives (for "postversion": "scripts/postversion.sh \"$npm_package_version\"" the portion that reads "scripts/postversion.sh \"$npm_package_version\"") can be changed, but _not to a value that is reliably cross platform_.
